/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/add-student` | `/add-student`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/edit-student` | `/edit-student`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/generate-qr` | `/generate-qr`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/students` | `/students`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/add-student` | `/add-student`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/edit-student` | `/edit-student`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/generate-qr` | `/generate-qr`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/students` | `/students`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/add-student${`?${string}` | `#${string}` | ''}` | `/add-student${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/edit-student${`?${string}` | `#${string}` | ''}` | `/edit-student${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/generate-qr${`?${string}` | `#${string}` | ''}` | `/generate-qr${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/students${`?${string}` | `#${string}` | ''}` | `/students${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/add-student` | `/add-student`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/edit-student` | `/edit-student`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/generate-qr` | `/generate-qr`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/students` | `/students`; params?: Router.UnknownInputParams; };
    }
  }
}
